# Generated by Django 5.1.2 on 2025-03-19 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_contact_base_contac_phone_n_f0c7db_idx_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GlobalPhonebook',
        ),
        migrations.DeleteModel(
            name='SpamRecord',
        ),
        migrations.RemoveIndex(
            model_name='contact',
            name='base_contac_phone_n_f0c7db_idx',
        ),
        migrations.RemoveIndex(
            model_name='spamreport',
            name='base_spamre_user_id_7e347d_idx',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='user',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='spamreport',
            old_name='user',
            new_name='reporter',
        ),
        migrations.RenameField(
            model_name='spamreport',
            old_name='reported_at',
            new_name='timestamp',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email_address',
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone_number',
            field=models.CharField(db_index=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(db_index=True, max_length=15, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='spamreport',
            unique_together={('reporter', 'phone_number')},
        ),
        migrations.AddIndex(
            model_name='spamreport',
            index=models.Index(fields=['reporter', 'phone_number'], name='base_spamre_reporte_93f902_idx'),
        ),
    ]
